pipeline:

  build:
    privileged: true
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t pttg-fs-ui .
    when:
      event: push

  test:
    privileged: true
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -f Dockerfile_test -t pttg-fs-ui-test .
      - docker run pttg-fs-ui-test
    when:
      event: push

  push:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=${DOCKER_PASSWORD} quay.io
      - docker tag pttg-fs-ui quay.io/ukhomeofficedigital/pttg-fs-ui:${DRONE_COMMIT_SHA}
      - docker tag pttg-fs-ui quay.io/ukhomeofficedigital/pttg-fs-ui:latest
      - docker push quay.io/ukhomeofficedigital/pttg-fs-ui:${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/pttg-fs-ui:latest
    when:
      event: push
      branch: master

  get-kube-configuration-deployment::
    image: plugins/git
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - git clone https://github.com/UKHomeOffice/kube-pttg-fs-ui.git
    when:
      event: [push, deployment]
      branch: master

  deploy-to-dev:
    image: quay.io/ukhomeofficedigital/kd:v0.2.3
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - KUBE_NAMESPACE=pt-i-dev
      - ENVIRONMENT=dev
      - VERSION=${DRONE_COMMIT_SHA}
      - KUBE_SERVER_DEV=https://kube-dev.dsp.notprod.homeoffice.gov.uk
    commands:
      - cd kube-pttg-fs-ui
      - ./deploy.sh
    when:
      event: push
      branch: master

  deploy-to-test:
    image: quay.io/ukhomeofficedigital/kd:v0.2.3
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - KUBE_NAMESPACE=pt-i-test
      - ENVIRONMENT=test
      - VERSION=${DRONE_COMMIT_SHA}
      - KUBE_SERVER_DEV=https://kube-dev.dsp.notprod.homeoffice.gov.uk
    commands:
      - cd kube-pttg-fs-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: test

  deploy-to-preprod:
    image: quay.io/ukhomeofficedigital/kd:v0.2.3
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - KUBE_NAMESPACE=pt-i-preprod
      - ENVIRONMENT=preprod
      - VERSION=${DRONE_COMMIT_SHA}
      - KUBE_SERVER_DEV=https://kube-dev.dsp.notprod.homeoffice.gov.uk
    commands:
      - cd kube-pttg-fs-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: preprod

  deploy-to-prod:
    image: quay.io/ukhomeofficedigital/kd:v0.2.3
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - KUBE_NAMESPACE=pt-i-prod
      - ENVIRONMENT=prod
      - VERSION=${DRONE_COMMIT_SHA}
      - KUBE_SERVER_PROD=https://kube.dsp.digital.homeoffice.gov.uk
    commands:
      - cd kube-pttg-fs-ui
      - ./deploy-prod.sh
    when:
      event: deployment
      environment: prod

services:
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
